// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtfifrwifpgegfynsgvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZmlmcndpZnBnZWdmeW5zZ3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDgxMjMsImV4cCI6MjA2NTg4NDEyM30.NCDfF6cvg7KkZsOUX3Jt20bf-iwd5ketojN2-XeTtJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);